name: 🏖️ 03 Coletor FDS (Sábado)

on:
  workflow_dispatch:

jobs:
  executar_fds:
    runs-on: ubuntu-latest
    
    # --- CONFIGURAÇÃO GLOBAL ---
    env:
      CPFL_USER: ${{ secrets.CPFL_USER }}
      CPFL_PASS: ${{ secrets.CPFL_PASS }}
      SP_CLIENT_ID: ${{ secrets.SP_CLIENT_ID }}
      SP_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
      SP_TENANT_ID: ${{ secrets.SP_TENANT_ID }}
      SP_SITE_URL: ${{ secrets.SP_SITE_URL }}

    defaults:
      run:
        working-directory: ./01_LEC

    steps:
      - name: 📥 1. Sincronizar Repositório
        uses: actions/checkout@v4

      - name: 🐍 2. Preparar Ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 3. Instalar Bibliotecas
        run: |
          pip install playwright requests
          playwright install chromium --with-deps

      - name: 🚀 4. Executar Script de FDS e Coletor
        # Aqui você coloca o nome do seu script que roda aos sábados
        # Se for o mesmo 00_Coletor.py, mantenha assim:
        run: python3 00b_Coletor_FDS.py
