name: Execucao Manual Coletor

on:
  workflow_dispatch:

jobs:
  rodar_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: |
          pip install playwright pytest-playwright office365-rest-python-client
          playwright install chromium --with-deps

      - name: Rodar Robo Coletor
        run: python 00_Coletor.py
        env:
          CPFL_USER: ${{ secrets.CPFL_USER }}
          CPFL_PASS: ${{ secrets.CPFL_PASS }}
          SP_USER: ${{ secrets.SP_USER }}
          SP_PASS: ${{ secrets.SP_PASS }}
          SP_SITE_URL: ${{ secrets.SP_SITE_URL }}
